project:
  type: website
  output-dir: docs

website:
  title: "Hydro Data"
  navbar:
    title: "Hydro Data"
    logo: www/inyo_logo.png
    left:
      - href: index.qmd
        text: Monitoring Well Data
      - flow.qmd
      - about.qmd
      - icon: github
        href: https://github.com/inyo-gov/hydro-data
    background: dark
    search: true

format:
  html:
    theme: cosmo
    linkcolor: "#2E86AB"
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    fig-responsive: true
    table-responsive: false
    fig-dir: figure-html
    subtitle: "Inyo County, California"
    footer: "Â© 2026 Inyo County, California. All rights reserved."

editor: visual

